### ISSUE TITLE
does not work on two input fileGrps anymore

### ISSUE THREAD

**Issue by bertsky** [JKamlah/ocrd_pagetopdf#21]
```
ocrd-pagetopdf -I OCR-D-OCR,OCR-D-BIN-WAN -O OCR-D-OUT -P textequiv_level word -P multipage merged --overwrite
Traceback (most recent call last): File "/data/ocr-d/ocrd_all/venv/bin/ocrd", line 8, in <module> sys.exit(cli())
 File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx)
 File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) 
File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params)
 File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs)
 File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd/cli/bashlib.py", line 115, in bashlib_input_files for input_file in processor.input_files:
 File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd/processor/base.py", line 291, in input_files assert len(ret[0]) == 1, 'Use zip_input_files() instead of input_files when processing multiple input fileGrps'
 AssertionError: Use zip_input_files() instead of input_files when processing multiple input fileGrps 13:54:28.798
```

**Comment by stweil** [comment]
Is this a `core` issue? I see no `ocrd_pagetopdf` in the traceback. And there were no recent changes in `ocrd_pagetopdf` which could explain why something does not work anymore. When did it work the last time?

**Comment by bertsky** [comment]
> I see no `ocrd_pagetopdf` in the traceback.

That's because ocrd-pagetopdf uses bashlib.

**Comment by stweil** [comment]
`bashlib` is part of `core`. When did it work the last time for you? Maybe there was a change in `core` which caused the regression, so I'd have to run `git bisect`.

**Comment by bertsky** [comment]
Sure it is. The point is: ocrd-pagetopdf does not work anymore. There's been a change to `input_files` long ago, I don't remember. There's no use bisecting core – this must be fixed **here**.

**Comment by stweil** [comment]
Sure, but first of all I (or whoever fixes it) must know what changed and what changes are required here.
